"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-m9j#y!#s0m$4%qsma$eykhu)qyx39q-1k*q*2f&j%0)(anuv#s',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Projetos exibidos no site. Cada um lê da mesma árvore de pastas sincronizada
# pelo OneDrive Desktop, que tem uma pasta por ano (2024/2025/2026/...) e dentro
# de cada ano pastas de mês com uma subpasta "EVIDÊNCIAS ...". Configurados no
# .env em blocos numerados:
#   PROJECT_1_SLUG=meu-projeto
#   PROJECT_1_NAME=Meu Projeto
#   PROJECT_1_ROOT=C:\caminho\para\a\pasta-que-contem-os-anos
#   PROJECT_1_MATCH=texto que identifica a subpasta do projeto dentro de cada mês
#   PROJECT_1_DEDICATED_ROOT=false
# Deixe PROJECT_N_ROOT em branco para o projeto aparecer como "não configurado".
# PROJECT_N_MATCH é opcional; se vazio, usa PROJECT_N_NAME para localizar a subpasta.
# PROJECT_N_DEDICATED_ROOT=true quando o ROOT é uma pasta exclusiva deste projeto
# (então arquivos soltos numa pasta de evidências sem subpastas já são dele).
# Deixe false/em branco quando o ROOT é compartilhado com outros projetos (ex:
# a pasta geral de indicadores), para não misturar evidências de outros projetos
# em meses que ainda não têm a subpasta numerada de cada projeto.
def _load_projects():
    projects = []
    index = 1
    while True:
        slug = os.environ.get(f'PROJECT_{index}_SLUG')
        name = os.environ.get(f'PROJECT_{index}_NAME')
        root = os.environ.get(f'PROJECT_{index}_ROOT')
        match = os.environ.get(f'PROJECT_{index}_MATCH')
        dedicated_root = os.environ.get(f'PROJECT_{index}_DEDICATED_ROOT', '').strip().lower() in (
            '1', 'true', 'yes', 'sim',
        )
        if not slug and not name and not root:
            break
        slug = slug or f'projeto-{index}'
        projects.append({
            'slug': slug,
            'name': name or slug,
            'root': Path(root).resolve() if root else None,
            'match': match or name or slug,
            'dedicated_root': dedicated_root,
        })
        index += 1
    return projects


PROJECTS = _load_projects()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'files_viewer',
    'valuation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
