# Generated by Django 6.1 on 2026-08-18 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectYearValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_slug', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('project_slug', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ValuationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('base_value_note', models.CharField(blank=True, help_text='Explicação de como preencher o valor base quando ele não é um número fixo.', max_length=255)),
                ('quantity_label', models.CharField(default='Quantidade', max_length=80)),
                ('rationale', models.TextField(blank=True)),
                ('valuation_criteria', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='valuation.valuationcategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ValuationMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('factor_type', models.CharField(choices=[('multiply', 'Multiplicador fixo (ex: ×1.2)'), ('variable_multiply', 'Multiplicador com valor informado (ex: Impact Factor)'), ('add_per_unit', 'Bônus somado por unidade (ex: +(n×0.2))')], max_length=20)),
                ('factor_value', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('exclusive_group', models.CharField(blank=True, help_text='Multiplicadores com o mesmo grupo são mutuamente exclusivos (radio em vez de checkbox).', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipliers', to='valuation.valuationproduct')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValuationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('applied_multipliers', models.JSONField(blank=True, default=list)),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='valuation.projectyearvaluation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='valuation.valuationproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
