# Generated by Django 6.1 on 2026-08-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationentry',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='valuationentry',
            name='file_path',
            field=models.CharField(blank=True, help_text='Caminho relativo (dentro da pasta do projeto) do arquivo usado como evidência.', max_length=1024),
        ),
    ]
